---
- hosts: localhost
  connection: local
  become: true

  vars_files: vars/{{ ansible_distribution }}.yml

  tasks:
  - name: "install packages"
    package: 
      name:
        - chromium-browser
        - cifs-utils
        - code
        - copyq
        - curl
        - fdupes
        - figlet
        - htop
        - ipcalc
        - manpages-de
        - members
        - mmv
        - ncdu
        - net-tools
        - pwgen
        - tmux
        - tree
        - unzip
        - vim
      state: latest

  - name: "uninstall packages Linux Mint"
    package: 
      name:
        - firefox
        - thunderbird
        - rhythmbox
        - pix
        - drawing
        - hexchat
        - transmission-common
        - transmission-gtk
        - celluloid
      state: absent
    when: ansible_distribution == "Linux Mint"

  - name: "uninstall packages ubuntu"
    package: 
      name:
        - firefox
        - thunderbird
        - rhythmbox
        - gnome-mahjongg
        - gnome-mines
        - gnome-sudoku
        - aisleriot
        - shotwell
      state: absent
    when: ansible_distribution == "Ubuntu"

  - name: "bash-it Git Clone"
    git:
      repo: https://github.com/Bash-it/bash-it.git
      dest: /home/{{ username }}/.bash.it

  - name: "tmux-themepack Git Clone"
    git:
      repo: https://github.com/jimeh/tmux-themepack.git
      dest: /home/{{ username }}/.tmux-themepack

  - name: "tmux fonts pack Git Clone"
    git:
      repo: https://github.com/powerline/fonts.git
      dest: /tmp/fonts

  - name: "run local tmux fonts script"
    become_user: '{{ username }}'
    script: /tmp/fonts/install.sh

  - name: "copy Wallpaper File"
    copy:
      src: ../files/{{ background_image_name }}
      dest: '{{ background_destination }}'
      owner: 'root'
      group: 'root'

  - name: "create some folder to the user home directory"
    file:
      path: '{{ item.path }}' 
      owner: '{{ username }}'
      group: '{{ username }}'
      state: directory
      mode: '0755'
    with_items:
      - {path: '/home/{{ username }}/scripts'}
      - {path: '/home/{{ username }}/.config/bpytop'}
      - {path: '/home/{{ username }}/.config/copyq'}

  - name: "copy some config files to the user home directory"
    copy: 
      src: '{{ item.src }}' 
      dest: '{{ item.dest }}'
      owner: '{{ username }}'
      group: '{{ username }}'
      mode: '0755'
    with_items:
      - { src: '../files/config_base', dest: '/home/{{ username }}/scripts/config_base.sh' }
      - { src: '../files/bashrc', dest: '/home/{{ username }}/.bashrc' }
      - { src: '../files/vimrc', dest: '/home/{{ username }}/.vimrc' }
      - { src: '../files/gitconfig', dest: '/home/{{ username }}/.gitconfig' }
      - { src: '../files/tmux', dest: '/home/{{ username }}/.tmux.conf' }
      - { src: '../files/copyq', dest: '/home/{{ username }}/.config/copyq/copyq.conf' }
      - { src: '../files/bpytop', dest: '/home/{{ username }}/.config/bpytop/bpytop.conf' }

  - name: "run local config script"
    become_user: '{{ username }}'
    script: /home/{{ username }}/scripts/config_base.sh

  - name: "add ansible service user for cron job"
    user:
      name: '{{ serviceuser }}'
      system: yes

  - name: "set up sudo for ansible service user"
    copy:
      src: ../files/sudoer_{{ serviceuser }}
      dest: /etc/sudoers.d/{{ serviceuser }}
      owner: 'root'
      group: 'root'
      mode: '0440'

  - name: "add ansible-pull cron job"
    cron:
      name: ansible auto-provision
      user: '{{ serviceuser }}'
      hour: "*/3"
      job: ansible-pull -o -U https://github.com/hth73/ansible-wks.git playbooks/ansible_base.yml

  - name: "Remove /tmp/fonts directory"
    file:
      path: /tmp/fonts
      state: absent

  - name: "update and upgrade apt repo"
    apt:
      upgrade: 'safe'
      update_cache: yes 
      force_apt_get: yes 
      cache_valid_time: '43200'
