# Path to your oh-my-zsh installation.
export ZSH="/home/hth/.oh-my-zsh"

# Set name of the theme to load --- if set to "random", it will
ZSH_THEME="eastwood"

# Uncomment one of the following lines to change the auto-update behavior
zstyle ':omz:update' mode reminder  # just remind me to update when it's time

# Uncomment the following line to change how often to auto-update (in days).
zstyle ':omz:update' frequency 14

# Which plugins would you like to load?
# Standard plugins can be found in $ZSH/plugins/
# Custom plugins may be added to $ZSH_CUSTOM/plugins/
plugins=(ansible aws direnv docker git kubectl minikube nmap pass sudo terraform)

source $ZSH/oh-my-zsh.sh


# ----- My ~/.zshrc User configuration ----- #

# color manpages
alias man="LANG=de_DE.UTF-8 man"
export LESS_TERMCAP_mb=$'\e[1;32m'
export LESS_TERMCAP_md=$'\e[1;32m'
export LESS_TERMCAP_me=$'\e[0m'
export LESS_TERMCAP_se=$'\e[0m'
export LESS_TERMCAP_so=$'\e[01;33m'
export LESS_TERMCAP_ue=$'\e[0m'
export LESS_TERMCAP_us=$'\e[1;4;31m'

# manage history file
export HISTFILE=~/.zsh_history
export HISTSIZE=100000
export HISTFILESIZE=100000

PROMPT_COMMAND="history -a; history -c; history -r; $PROMPT_COMMAND"
HISTORY_IGNORE="(h|history|x|exit|c|clear|pwd|up|ver|app|conf|tf|pac|ls|cd|pwd12|pwd18|pwd24|tr|pwgen)"

setopt INC_APPEND_HISTORY     # commands are added to the history immediately
setopt EXTENDED_HISTORY       # record timestamp of command in HISTFILE
setopt HIST_IGNORE_SPACE      # ignore commands that start with space
setopt HIST_EXPIRE_DUPS_FIRST # delete duplicates first when HISTFILE size exceeds HISTSIZE
setopt HIST_IGNORE_DUPS       # ignore duplicated commands history list
setopt HIST_IGNORE_ALL_DUPS
setopt HIST_FIND_NO_DUPS
setopt HIST_SAVE_NO_DUPS
setopt HIST_VERIFY            # show command with history expansion to user before running it
setopt SHARE_HISTORY          # share command history data

# load all my ssh key
if [ -z "$SSH_AUTH_SOCK" ] ; then
    eval `ssh-agent`
    grep -slR "PRIVATE" ~/.ssh/ | xargs ssh-add
fi

# direnv hook for zsh
eval "$(direnv hook zsh)"

## to expand the $PATH Variable
export PATH=$HOME/bin:/usr/local/bin:$PATH

## concourse and fly
# export HTTPS_PROXY="socks5://127.0.0.1:3333"

## set $JAVA_HOME
if [ -f "$(which javac)" ]; then
     export JAVA_HOME=$(dirname $(dirname $(readlink -e $(which javac))))
fi

# my default working directory
if [ -d ~/repo ] ; then
   cd ~/repo
else
   cd ~
fi

# function create and switch folder
function mkcd () {
   mkdir "$1" && cd "$1"
}

# start commands with sudo rights
if [ $UID -ne 0 ]; then
    alias reboot='sudo reboot'
    alias shutdown='sudo shutdown -h now'
    alias update='sudo apt update && sudo apt upgrade -y && sudo apt autoremove -y'
    alias disk='sudo ncdu'
    alias cmount='mount | column -t'
    alias caconf='sudo dpkg-reconfigure ca-certificates'
fi

## my aliases
alias h='history -i'
alias x='exit'
alias up='uptime'
alias ver='lsb_release -dr && uname -snrm'
alias app='dpkg -l | grep $var1'
alias vi='vim'
alias btop='bpytop'
alias sub='/opt/sublime_text/sublime_text'
alias cfg='sub ~/.zshrc'
alias pull='for i in */.git; do ( echo $i; cd $i/..; git pull; ); done'
alias -s {yml,yaml,txt,json,sh,py,md,hcl,tf}=sub
alias d='dirs -v | head -10'
alias pwd12='openssl rand -base64 12'
alias pwd18='openssl rand -base64 18'
alias pwd24='openssl rand -base64 24'

alias ll='ls -lh'
alias lr='ls -laihR'
alias la='ls -laihF'
alias l='ls -CF'

alias ..='cd ..'
alias ...='cd ../..'
alias ....='cd ../../..'
alias .....='cd ../../../..'

alias repo='$repo'
alias conf='$config'
alias pac='$packer'
alias tf='$terraform'
