#!/usr/bin/env bash
set -e

# ======================================================================
#   Bash script to set desktop and nemo/nautilus settings
# ======================================================================

source /etc/os-release

if [[ "$NAME" = "Ubuntu" ]]; 
then
  gsettings set org.gnome.desktop.background picture-uri 'file:///usr/share/backgrounds/background.jpg'
  gsettings set org.gnome.desktop.background picture-options 'zoom'
  gsettings set org.gnome.desktop.screensaver picture-uri 'file:///usr/share/backgrounds/background.jpg'
  gsettings set org.gnome.desktop.screensaver picture-options 'zoom'

  gsettings set org.gnome.nautilus.preferences default-folder-viewer 'list-view'
  gsettings set org.gnome.nautilus.preferences always-use-location-entry true
  gsettings set org.gnome.nautilus.list-view default-zoom-level 'small'
  gsettings set org.gtk.Settings.FileChooser show-hidden true

  gsettings set org.gnome.shell.extensions.desktop-icons show-home false
  gsettings set org.gnome.shell.extensions.desktop-icons show-trash false
  gsettings set org.gnome.shell.extensions.dash-to-dock dash-max-icon-size '28'
  gsettings set org.gnome.shell.extensions.dash-to-dock show-trash true

  gsettings set org.gnome.desktop.screensaver lock-enabled false

elif [[ "$NAME" = "Linux Mint" ]]
then
  gsettings set org.cinnamon.desktop.background picture-uri 'file:///usr/share/backgrounds/linuxmint/background.jpg'
  gsettings set org.cinnamon.desktop.background picture-options 'zoom'
  gsettings set org.mate.background picture-filename 'file:///usr/share/backgrounds/linuxmint/background.jpg'
  gsettings set org.mate.background picture-options 'zoom'

  gsettings set org.nemo.preferences show-computer-icon-toolbar true
  gsettings set org.nemo.preferences show-open-in-terminal-toolbar true
  gsettings set org.nemo.preferences show-new-folder-icon-toolbar true
  gsettings set org.nemo.preferences show-edit-icon-toolbar true
  gsettings set org.nemo.preferences show-home-icon-toolbar true
  gsettings set org.nemo.preferences show-hidden-files true
  gsettings set org.nemo.preferences default-folder-viewer 'list-view'
  gsettings set org.nemo.preferences inherit-folder-viewer true
  gsettings set org.nemo.preferences show-location-entry true

  gsettings set org.nemo.desktop computer-icon-visible false
  gsettings set org.nemo.desktop home-icon-visible false
  gsettings set org.nemo.desktop volumes-visible false
  gsettings set org.nemo.desktop show-orphaned-desktop-icons false

  gsettings set org.cinnamon.desktop.screensaver lock-enabled false

  gsettings set org.cinnamon panels-height "['1:28']" 

else
  echo "Das Betriebssystem ist weder ein Ubuntu noch ein Linux Mint, das Script wird beendet."

fi